% Generates the QPP parameter ROM (VHDL package) and a golden CSV from the
% authoritative TS36.212 Table 5.1.3-3 embedded in internal_interleaver.m.
%
% The `parameters` literal is parsed straight out of internal_interleaver.m
% (not hand-transcribed), so the ROM cannot drift from the software model.
% Per row: d0 = mod(f1+f2, K), step = mod(2*f2, K)  (both < K, pre-reduced).

repo_root = fileparts(fileparts(mfilename('fullpath')));

src = fileread(fullfile(repo_root, 'internal_interleaver.m'));
tok = regexp(src, 'parameters\s*=\s*\[([^\]]*)\]', 'tokens', 'once');
if isempty(tok)
    error('generate_hdl_qpp_rom:ParseFailed', ...
        'Could not locate the parameters table in internal_interleaver.m');
end
P = str2num(['[' tok{1} ']']); %#ok<ST2NM>  % N x 3 : [K f1 f2]
N = size(P, 1);

K    = P(:,1);
f1   = P(:,2);
f2   = P(:,3);
d0   = mod(f1 + f2, K);
step = mod(2 .* f2, K);

W = 13;  % LTE max K = 6144 < 2^13
if max(K) >= 2^W
    error('generate_hdl_qpp_rom:WidthTooSmall', 'K exceeds %d-bit width', W);
end

% --- golden CSV ---
csv_dir = fullfile(repo_root, 'hdl', 'vectors');
if ~exist(csv_dir, 'dir')
    mkdir(csv_dir);
end
csv_path = fullfile(csv_dir, 'qpp_rom.csv');
fid = fopen(csv_path, 'w');
if fid < 0
    error('generate_hdl_qpp_rom:OpenFailed', 'Cannot open %s', csv_path);
end
co = onCleanup(@() fclose(fid));
fprintf(fid, 'K,d0,step\n');
for i = 1:N
    fprintf(fid, '%d,%d,%d\n', K(i), d0(i), step(i));
end
clear co;

% --- VHDL package ---
vhd_path = fullfile(repo_root, 'hdl', 'rtl', 'qpp_rom_pkg.vhd');
fv = fopen(vhd_path, 'w');
if fv < 0
    error('generate_hdl_qpp_rom:OpenFailed', 'Cannot open %s', vhd_path);
end
cv = onCleanup(@() fclose(fv));

fprintf(fv, '-- AUTO-GENERATED by scripts/generate_hdl_qpp_rom.m\n');
fprintf(fv, '-- Source: TS36.212 Table 5.1.3-3 in internal_interleaver.m. Do not edit by hand.\n\n');
fprintf(fv, 'library ieee;\nuse ieee.std_logic_1164.all;\nuse ieee.numeric_std.all;\n\n');
fprintf(fv, 'package qpp_rom_pkg is\n');
fprintf(fv, '  constant QPP_W     : integer := %d;\n', W);
fprintf(fv, '  constant QPP_ROM_N : integer := %d;\n', N);
fprintf(fv, '  type qpp_entry_t is record\n');
fprintf(fv, '    k    : unsigned(QPP_W-1 downto 0);\n');
fprintf(fv, '    d0   : unsigned(QPP_W-1 downto 0);\n');
fprintf(fv, '    step : unsigned(QPP_W-1 downto 0);\n');
fprintf(fv, '  end record;\n');
fprintf(fv, '  type qpp_rom_t is array (0 to QPP_ROM_N-1) of qpp_entry_t;\n');
fprintf(fv, '  constant QPP_TABLE : qpp_rom_t := (\n');
for i = 1:N
    sep = ',';
    if i == N
        sep = '';
    end
    fprintf(fv, ['    %d => (k => to_unsigned(%d, QPP_W), ' ...
        'd0 => to_unsigned(%d, QPP_W), ' ...
        'step => to_unsigned(%d, QPP_W))%s\n'], ...
        i-1, K(i), d0(i), step(i), sep);
end
fprintf(fv, '  );\n');
fprintf(fv, 'end package qpp_rom_pkg;\n');
clear cv;

fprintf('Wrote %s (%d entries) and %s\n', vhd_path, N, csv_path);
