library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.qpp_rom_pkg.all;

-- ===========================================================================
-- turbo_decoder_top : fixed-point iterative Max-Log-MAP turbo-decode loop
-- (TS36.212 SS5.1.3.2), P2 of the staged decoder plan in
-- hdl/docs/decoder_roadmap.md. It wraps the P1 constituent_decoder UNMODIFIED
-- inside the half-iteration loop algebra, exchanging extrinsic information
-- through the reused qpp_rom + qpp_interleaver across H = round(2*max_iter)
-- half-iterations, then makes a hard decision over the K systematic bits.
--
-- ---------------------------------------------------------------------------
-- BIT-EXACT CONTRACT (must match the authored oracle exactly; the cocotb lane,
-- task 4.x, asserts bit-for-bit vs vectors derived from it):
--   ORACLE  = scripts/fixedpoint_turbo_decoder.m  (loop semantics, de-mux
--             indexing, saturating exchange arithmetic, re-quantization points,
--             half-iteration framing). The inner BCJR is the P1 reference
--             scripts/fixedpoint_constituent_decoder.m, ported in
--             hdl/rtl/constituent_decoder.vhdl (instantiated here UNMODIFIED).
--   DESIGN  = openspec/changes/add-fpga-turbo-decode-loop/design.md +
--             hdl/docs/p2_turbo_loop_design_seed.md.
--
--   PINNED Q-FORMAT (inherited, NOT re-derived):
--     * core / parity / termination / core-input words : W_IN  = 9 (Q4.4,
--       F_in = 4).  These are direct constituent_decoder inputs.
--     * stored exchange words ch_sys, c_a, c_e          : W_EXT = 12 (Q7.4).
--     * combiner accumulator (c_a+ch_sys, x_e+ch_sys,
--       c_a+c_e)                                        : W_ACC = 14, saturating,
--       then re-quantized (saturating) to W_EXT (store) / W_IN (core input).
--     * shared fractional scale F_in = 4  ->  the exchange<->core boundary is a
--       pure width/saturate, no rescaling.  P1 +/-inf sentinel inherited inside
--       the core (no new token here).
--
--   LOOP ALGEBRA (per design.md decision 1; persistent z_a/z'_a/ch_sys set once
--   at load, cyclic c_a/c_e per half; even h = UPPER, odd h = LOWER):
--     UPPER : x_a[0..K-1] = sat_to_in( c_a + ch_sys )   (W_ACC accum -> W_IN)
--             x_e         = constituent_decoder(x_a, z_a)
--             c_e[0..K-1] = sat_to_ext( x_e[0..K-1] + ch_sys )  (W_ACC -> W_EXT)
--     LOWER : x'_a[0..K-1] = sat_to_in( c_e[pi[k]] )     (interleave read)
--             x'_e         = constituent_decoder(x'_a, z'_a)
--             c_a[pi[k]]   = sat_to_ext( x'_e[0..K-1] )  (deinterleave scatter)
--     FINAL : c[k] = ( sat_add_acc(c_a[k], c_e[k]) ) < 0
--   The 3 termination extrinsics x_e[K..K+2] are DISCARDED.
--
--   REVERSE-x_e GOTCHA (CRITICAL): constituent_decoder streams its extrinsic
--   output in BACKWARD-SWEEP order -- index N-1 first (N = K+3), index 0 last,
--   with out_last asserted on index 0.  So the 3 termination extrinsics
--   (indices K, K+1, K+2) arrive FIRST and the body indices K-1..0 follow.
--   This controller un-reverses in hardware by maintaining a down-counter that
--   starts at N-1 on the first out_valid and decrements each valid beat; the
--   captured x_e code is written to the body memory at that index (only when
--   the index is < K), giving forward-order c_e / c_a exactly as the oracle's
--   forward-indexed arrays.  (The P1 cocotb lane un-reverses before its
--   forward-order CSV compare; this is the hardware equivalent.)
--
-- ARCHITECTURE: one constituent_decoder instance (sequential upper -> lower),
-- async-read LLR memories (sim-first, like prior tops; circular_buffer/
-- rate_matching_top precedent).  pi regenerated by qpp_interleaver per use (no
-- pi RAM).  Latency ~ 4*H*K cycles (constituent ~3*(K+3) per call x 2 calls +
-- ~2*K interleave/deinterleave per full iteration; H halves).
--
-- INTERFACE (repo convention: synchronous active-high rst; start latches K;
-- d_a streamed column-major as the encoder emits it; out_valid/out_last for the
-- K hard bits; busy/done status).  Mirrors turbo_encode_top / tx_chain_top.
--   Load protocol: after in_start (with k_in=K), stream the 3x(K+4) d_a matrix
--   as K+4 column beats on da_valid, each beat presenting d_a(1)/d_a(2)/d_a(3)
--   for that column on da1_in/da2_in/da3_in. These carry W_EXT signed codes:
--   the oracle quantizes the whole channel-LLR matrix to the W_EXT exchange
--   grid (Q7.4) at step 0, then re-saturates per de-muxed row internally
--   (ch_sys kept @ W_EXT; z_a/z'_a parity + termination triplets clipped to
--   W_IN at the load de-mux below). The golden CSV stores d_a at W_EXT, so the
--   ports MUST be W_EXT wide -- a W_IN port would clip channel LLRs that exceed
--   the W_IN range before storage and break the bit-exact contract.
-- ===========================================================================
entity turbo_decoder_top is
  generic (
    -- Inherited P1 core widths (defaults ARE the pin; forwarded to the core).
    W_IN    : integer := 9;    -- core input LLR (Q4.4, F_in=4)
    W_GAMMA : integer := 10;
    W_AB    : integer := 15;
    W_DELTA : integer := 17;
    W_XE    : integer := 18;   -- constituent extrinsic output width
    -- P2 exchange-format pins.
    W_EXT   : integer := 12;   -- stored c_a/c_e/ch_sys word (Q7.4)
    W_ACC   : integer := 14;   -- combiner accumulator
    -- Sizing.
    W_K     : integer := 13;   -- K width (LTE max K=6144 -> 13 bits)
    K_MAX   : integer := 6144; -- max block length
    -- User-approved: max iterations as a generic (default 8 -> H=16).
    MAX_ITERATIONS : integer := 8
  );
  port (
    clk       : in  std_logic;
    rst       : in  std_logic;                          -- sync, active-high
    in_start  : in  std_logic;                          -- latch K, begin load
    k_in      : in  std_logic_vector(W_K-1 downto 0);   -- block length K
    -- LOAD: K+4 column beats of the 3x(K+4) d_a matrix (column-major).
    -- d_a arrives on the W_EXT exchange grid (Q7.4, [-2048,2047]): the oracle
    -- (fixedpoint_turbo_decoder.m step 0) quantizes the channel-LLR matrix to
    -- W_EXT, then re-saturates each de-muxed row to its own width internally
    -- (ch_sys @ W_EXT, z_a/z'_a parity + termination triplets @ W_IN). The
    -- golden CSV stores d_a at W_EXT, so these ports MUST be W_EXT wide; the
    -- per-row requantize-to-W_IN happens in the load de-mux below (z_a/z'_a/
    -- termination) and at the core input (ch_sys-derived x_a). A W_IN port here
    -- would clip channel LLRs before storage and break bit-exactness.
    da_valid  : in  std_logic;
    da1_in    : in  std_logic_vector(W_EXT-1 downto 0); -- d_a(1,col): systematic
    da2_in    : in  std_logic_vector(W_EXT-1 downto 0); -- d_a(2,col): upper parity
    da3_in    : in  std_logic_vector(W_EXT-1 downto 0); -- d_a(3,col): lower parity
    -- OUTPUT: K hard-decision bits, c[0] first.
    out_valid : out std_logic;
    out_last  : out std_logic;
    c_out     : out std_logic;
    -- status
    busy      : out std_logic;
    done      : out std_logic                           -- one-cycle pulse
  );
end entity turbo_decoder_top;

architecture rtl of turbo_decoder_top is

  constant N_MAX : integer := K_MAX + 3;   -- core block length max = K+3

  -- Half-iteration count: H = round(2*MAX_ITERATIONS). MAX_ITERATIONS is an
  -- integer generic so 2*MAX_ITERATIONS is already integral (round is a no-op);
  -- kept explicit to mirror the oracle's H = round(2*max_iterations).
  constant H : integer := 2 * MAX_ITERATIONS;

  -- Saturation bounds (mirror the .m: in_*, ext_*, acc_*).
  constant IN_MIN  : integer := -(2**(W_IN  - 1));
  constant IN_MAX  : integer :=  (2**(W_IN  - 1)) - 1;
  constant EXT_MIN : integer := -(2**(W_EXT - 1));
  constant EXT_MAX : integer :=  (2**(W_EXT - 1)) - 1;
  constant ACC_MIN : integer := -(2**(W_ACC - 1));
  constant ACC_MAX : integer :=  (2**(W_ACC - 1)) - 1;

  -- ---- Reused cores (UNMODIFIED), declared as components. ----
  component constituent_decoder is
    generic (
      W_IN    : integer := 9;
      W_GAMMA : integer := 10;
      W_AB    : integer := 15;
      W_DELTA : integer := 17;
      W_XE    : integer := 18;
      W_K     : integer := 13;
      N_MAX   : integer := 6147
    );
    port (
      clk       : in  std_logic;
      rst       : in  std_logic;
      start     : in  std_logic;
      k_in      : in  std_logic_vector(W_K-1 downto 0);
      in_valid  : in  std_logic;
      x_a_in    : in  std_logic_vector(W_IN-1 downto 0);
      z_a_in    : in  std_logic_vector(W_IN-1 downto 0);
      out_valid : out std_logic;
      out_last  : out std_logic;
      x_e_out   : out std_logic_vector(W_XE-1 downto 0);
      busy      : out std_logic;
      done      : out std_logic
    );
  end component;

  component qpp_rom is
    port (
      clk : in std_logic; rst : in std_logic; start : in std_logic;
      k_in : in std_logic_vector(QPP_W-1 downto 0);
      done : out std_logic; supported : out std_logic;
      d0_o : out std_logic_vector(QPP_W-1 downto 0);
      step_o : out std_logic_vector(QPP_W-1 downto 0)
    );
  end component;

  component qpp_interleaver is
    generic ( W : integer := 13 );
    port (
      clk : in std_logic; rst : in std_logic; start : in std_logic;
      k_in : in std_logic_vector(W-1 downto 0);
      d0 : in std_logic_vector(W-1 downto 0);
      step : in std_logic_vector(W-1 downto 0);
      valid : out std_logic; last : out std_logic;
      pi_o : out std_logic_vector(W-1 downto 0)
    );
  end component;

  -- ---- LLR / extrinsic memories (integer codes). ----
  -- Persistent (set once at load):
  type in_mem_t  is array (0 to N_MAX-1) of integer;  -- W_IN-grid words
  signal za_mem  : in_mem_t;   -- z_a[0..K+2]  (upper parity + termination)
  signal zpa_mem : in_mem_t;   -- z'_a[0..K+2] (lower parity + termination)
  -- ch_sys lives on the W_EXT grid (feeds the accumulator adds); body only.
  type ext_mem_t is array (0 to K_MAX-1) of integer;  -- W_EXT-grid words
  signal chs_mem : ext_mem_t;  -- ch_sys[0..K-1]
  -- Termination triplets for the upper/lower core input (W_IN grid, constant).
  type term_t is array (0 to 2) of integer;
  signal xa_term  : term_t;    -- x_a[K..K+2]
  signal xpa_term : term_t;    -- x'_a[K..K+2]
  -- Cyclic state (W_EXT grid):
  signal ca_mem : ext_mem_t;   -- c_a[0..K-1] interleaved extrinsic (state)
  signal ce_mem : ext_mem_t;   -- c_e[0..K-1] upper-decoder cyclic extrinsic

  signal Kr : integer range 0 to K_MAX := 0;
  signal Nr : integer range 0 to N_MAX := 0;   -- N = K+3

  -- ---- FSM. ----
  -- S_HALF_DISPATCH branches even -> UPPER (build/dec/ce), odd -> LOWER
  -- (interleave/dec/deinterleave).  See design.md decision 8 / seed S5.
  -- The c_e accumulate (S_UP_CE) is folded into the upper capture state and
  -- the deinterleave scatter (S_LO_DILV) into S_LO_PI2; the design.md sketch
  -- names them as conceptual sub-steps, here merged to avoid extra passes.
  type state_t is (
    S_IDLE, S_LOAD_D,
    -- K is constant, so the ROM (K -> d0,step) is looked up ONCE after load
    -- and the result cached; lower halves only re-run the interleaver.
    S_ROM_START, S_ROM_WAIT,
    S_HALF_DISPATCH,
    -- upper half  (S_UP_BUILD/S_UP_DEC/S_UP_CE folded into S_UP_DEC)
    S_UP_DEC,
    -- lower half  (S_LO_ILV = PI1 interleave read; S_LO_DEC; S_LO_DILV =
    -- PI2 deinterleave scatter, folded into S_LO_PI2). Each PI phase pulses
    -- qi_start then waits for qi_valid in its *_WAIT substate.
    S_LO_PI1_START, S_LO_PI1, S_LO_DEC, S_LO_PI2_START, S_LO_PI2,
    -- finish
    S_FINAL, S_OUT, S_DONE);
  signal st : state_t := S_IDLE;

  signal h_cnt : integer range 0 to H + 1 := 0;   -- half-iteration index

  -- Load counters.
  signal lcol : integer range 0 to K_MAX + 4 := 0;   -- d_a column index

  -- Core feed / capture.
  signal cd_start    : std_logic := '0';
  signal cd_in_valid : std_logic := '0';
  signal cd_xa       : std_logic_vector(W_IN-1 downto 0) := (others => '0');
  signal cd_za       : std_logic_vector(W_IN-1 downto 0) := (others => '0');
  signal cd_out_valid: std_logic;
  signal cd_out_last : std_logic;
  signal cd_xe       : std_logic_vector(W_XE-1 downto 0);
  signal cd_busy     : std_logic;
  signal cd_done     : std_logic;
  signal cd_k        : std_logic_vector(W_K-1 downto 0) := (others => '0');

  signal feed_idx : integer range 0 to N_MAX := 0;   -- core-input stream index
  signal cap_idx  : integer range 0 to N_MAX := 0;   -- core-output (reverse) idx
  signal cap_seen : std_logic := '0';                -- first out_valid seen?

  -- QPP address generation.
  signal rom_start, rom_done, rom_sup : std_logic := '0';
  signal rom_d0, rom_step : std_logic_vector(QPP_W-1 downto 0);
  signal d0c, stepc       : std_logic_vector(QPP_W-1 downto 0) := (others => '0');
  signal qi_start, qi_valid, qi_last : std_logic := '0';
  signal qi_pi  : std_logic_vector(QPP_W-1 downto 0);

  -- pi capture: x'_a body = c_e[pi] interleave read (PI1) and deinterleave
  -- scatter c_a[pi] = x'_e (PI2). We need pi indexed by k=0..K-1; the
  -- qpp_interleaver streams pi(0),pi(1),... in order. For PI1 we gather c_e[pi]
  -- into a forward buffer xpa_body; for PI2 we replay pi to scatter the
  -- forward-order x'_e body into c_a.
  signal xpa_body : ext_mem_t;          -- interleaved core-input body (W_EXT)
  signal xpe_body : ext_mem_t;          -- captured x'_e body (W_EXT-clipped)
  signal pi_k     : integer range 0 to K_MAX := 0;   -- pi-stream index k

  -- Output streaming.
  signal out_idx : integer range 0 to K_MAX := 0;
  signal ov, ol, dn, bsy : std_logic := '0';
  signal cbit : std_logic := '0';

  -- Saturating helpers (scalar signed integer, clamp - no wrap; mirror the .m).
  function sat_clip(x, lo, hi : integer) return integer is
  begin
    if x > hi then return hi;
    elsif x < lo then return lo;
    else return x; end if;
  end function;

  function sat_add(a, b, lo, hi : integer) return integer is
    variable s : integer;
  begin
    s := a + b;
    if s > hi then return hi;
    elsif s < lo then return lo;
    else return s; end if;
  end function;

begin
  -- ---- Core instantiations (UNMODIFIED). ----
  u_cd : constituent_decoder
    generic map (W_IN => W_IN, W_GAMMA => W_GAMMA, W_AB => W_AB,
                 W_DELTA => W_DELTA, W_XE => W_XE, W_K => W_K, N_MAX => N_MAX)
    port map (clk => clk, rst => rst, start => cd_start, k_in => cd_k,
              in_valid => cd_in_valid, x_a_in => cd_xa, z_a_in => cd_za,
              out_valid => cd_out_valid, out_last => cd_out_last,
              x_e_out => cd_xe, busy => cd_busy, done => cd_done);

  u_rom : qpp_rom
    port map (clk => clk, rst => rst, start => rom_start,
              k_in => std_logic_vector(to_unsigned(Kr, QPP_W)),
              done => rom_done, supported => rom_sup,
              d0_o => rom_d0, step_o => rom_step);

  u_qi : qpp_interleaver
    generic map (W => QPP_W)
    port map (clk => clk, rst => rst, start => qi_start,
              k_in => std_logic_vector(to_unsigned(Kr, QPP_W)),
              d0 => d0c, step => stepc,
              valid => qi_valid, last => qi_last, pi_o => qi_pi);

  cd_k <= std_logic_vector(to_unsigned(Kr, W_K));

  -- Status / outputs.
  out_valid <= ov;
  out_last  <= ol;
  c_out     <= cbit;
  busy      <= bsy;
  done      <= dn;

  process (clk)
    variable pi_idx  : integer;
    variable acc     : integer;
    variable xe_code : integer;
    variable za_v, xa_v : integer;
  begin
    if rising_edge(clk) then
      -- default deassertions
      cd_start    <= '0';
      cd_in_valid <= '0';
      rom_start   <= '0';
      qi_start    <= '0';
      ov          <= '0';
      ol          <= '0';
      dn          <= '0';

      if rst = '1' then
        st  <= S_IDLE;
        bsy <= '0';
      else
        case st is

          -- =============================================================
          when S_IDLE =>
            if in_start = '1' then
              Kr   <= to_integer(unsigned(k_in));
              Nr   <= to_integer(unsigned(k_in)) + 3;
              lcol <= 0;
              bsy  <= '1';
              st   <= S_LOAD_D;
            end if;

          -- ---- LOAD: de-mux the 3x(K+4) d_a column stream. -------------
          -- Column k (0..K-1) body:  ch_sys[k]=d_a(1), z_a[k]=d_a(2),
          --                          z'_a[k]=d_a(3).
          -- Termination columns K..K+3 -> x_a/z_a[K..K+2], x'_a/z'_a[K..K+2]
          --   per the oracle de-mux (turbo_decoder.m lines 80-94):
          --     x_a(K+1)=d_a(1,K+1) z_a(K+1)=d_a(2,K+1)
          --     x_a(K+2)=d_a(3,K+1) z_a(K+2)=d_a(1,K+2)
          --     x_a(K+3)=d_a(2,K+2) z_a(K+3)=d_a(3,K+2)
          --     x'_a(K+1)=d_a(1,K+3) z'_a(K+1)=d_a(2,K+3)
          --     x'_a(K+2)=d_a(3,K+3) z'_a(K+2)=d_a(1,K+4)
          --     x'_a(K+3)=d_a(2,K+4) z'_a(K+3)=d_a(3,K+4)
          -- (1-based .m -> here 0-based: column "K+1".m == lcol K, etc.;
          --  the termination triplet entry j=0..2 == array index K+j.)
          -- d_a arrives on the W_EXT grid (range [-2048,2047]); the oracle
          -- stores ch_sys at W_EXT but re-saturates the parity (z_a/z'_a) and
          -- termination triplets to the core input grid W_IN (sat_round to
          -- W_in == sat_clip of the W_ext code to W_in, since the W_ext round
          -- never saturates these LLRs). So clip every parity/termination
          -- store to [IN_MIN,IN_MAX] here; ch_sys keeps the W_EXT clip.
          when S_LOAD_D =>
            if da_valid = '1' then
              if lcol < Kr then
                -- body column
                chs_mem(lcol) <= sat_clip(to_integer(signed(da1_in)),
                                          EXT_MIN, EXT_MAX);
                za_mem(lcol)  <= sat_clip(to_integer(signed(da2_in)),
                                          IN_MIN, IN_MAX);
                zpa_mem(lcol) <= sat_clip(to_integer(signed(da3_in)),
                                          IN_MIN, IN_MAX);
              elsif lcol = Kr then
                -- termination column index 0 (== .m column K+1)
                xa_term(0)    <= sat_clip(to_integer(signed(da1_in)),
                                          IN_MIN, IN_MAX);  -- x_a(K+1)
                za_mem(Kr)    <= sat_clip(to_integer(signed(da2_in)),
                                          IN_MIN, IN_MAX);  -- z_a(K+1)
                xa_term(1)    <= sat_clip(to_integer(signed(da3_in)),
                                          IN_MIN, IN_MAX);  -- x_a(K+2)
              elsif lcol = Kr + 1 then
                -- .m column K+2
                za_mem(Kr+1)  <= sat_clip(to_integer(signed(da1_in)),
                                          IN_MIN, IN_MAX);  -- z_a(K+2)
                xa_term(2)    <= sat_clip(to_integer(signed(da2_in)),
                                          IN_MIN, IN_MAX);  -- x_a(K+3)
                za_mem(Kr+2)  <= sat_clip(to_integer(signed(da3_in)),
                                          IN_MIN, IN_MAX);  -- z_a(K+3)
              elsif lcol = Kr + 2 then
                -- .m column K+3
                xpa_term(0)   <= sat_clip(to_integer(signed(da1_in)),
                                          IN_MIN, IN_MAX);  -- x'_a(K+1)
                zpa_mem(Kr)   <= sat_clip(to_integer(signed(da2_in)),
                                          IN_MIN, IN_MAX);  -- z'_a(K+1)
                xpa_term(1)   <= sat_clip(to_integer(signed(da3_in)),
                                          IN_MIN, IN_MAX);  -- x'_a(K+2)
              else
                -- lcol = Kr + 3  (.m column K+4)
                zpa_mem(Kr+1) <= sat_clip(to_integer(signed(da1_in)),
                                          IN_MIN, IN_MAX);  -- z'_a(K+2)
                xpa_term(2)   <= sat_clip(to_integer(signed(da2_in)),
                                          IN_MIN, IN_MAX);  -- x'_a(K+3)
                zpa_mem(Kr+2) <= sat_clip(to_integer(signed(da3_in)),
                                          IN_MIN, IN_MAX);  -- z'_a(K+3)
              end if;

              if lcol = Kr + 3 then
                -- c_a = 0 init.
                for k in 0 to K_MAX-1 loop
                  ca_mem(k) <= 0;
                end loop;
                h_cnt <= 0;
                st    <= S_ROM_START;
              else
                lcol <= lcol + 1;
              end if;
            end if;

          -- ---- ROM lookup (K -> d0,step), done ONCE; result cached. ----
          when S_ROM_START =>
            rom_start <= '1';        -- pulsed; clears stale rom_done in the ROM
            st        <= S_ROM_WAIT;

          when S_ROM_WAIT =>
            if rom_done = '1' then
              -- rom_sup is '1' for every supported (golden) K; cache d0/step.
              d0c   <= rom_d0;
              stepc <= rom_step;
              st    <= S_HALF_DISPATCH;
            end if;

          -- ---- HALF-ITERATION DISPATCH. --------------------------------
          when S_HALF_DISPATCH =>
            if h_cnt = H then
              out_idx <= 0;
              st      <= S_FINAL;
            else
              -- prepare core feed (both halves stream the core input from
              -- index 0). Pulse cd_start now; feed begins next cycle.
              cd_start <= '1';
              feed_idx <= 0;
              cap_idx  <= 0;
              cap_seen <= '0';
              if (h_cnt mod 2) = 0 then
                -- UPPER half: x_a body = sat_to_in(c_a + ch_sys), then term.
                st <= S_UP_DEC;
              else
                -- LOWER half: build x'_a body = c_e[pi] via the interleaver.
                st <= S_LO_PI1_START;
              end if;
            end if;

          -- =================== UPPER half =============================
          -- Feed the core: indices 0..K-1 = sat_to_in(c_a+ch_sys),
          -- indices K..K+2 = xa_term, paired with z_a[0..K+2].
          -- Capture x_e (reverse order), store c_e[k]=sat_to_ext(x_e[k]+ch_sys)
          -- for k<K (discard k>=K termination extrinsics).
          when S_UP_DEC =>
            -- drive the core load stream
            if feed_idx < Nr then
              if feed_idx < Kr then
                acc  := sat_add(ca_mem(feed_idx), chs_mem(feed_idx),
                                ACC_MIN, ACC_MAX);
                xa_v := sat_clip(acc, IN_MIN, IN_MAX);
              else
                xa_v := xa_term(feed_idx - Kr);
              end if;
              za_v := za_mem(feed_idx);
              cd_xa       <= std_logic_vector(to_signed(xa_v, W_IN));
              cd_za       <= std_logic_vector(to_signed(za_v, W_IN));
              cd_in_valid <= '1';
              feed_idx    <= feed_idx + 1;
            end if;
            -- capture the reverse-order extrinsic stream
            if cd_out_valid = '1' then
              if cap_seen = '0' then
                cap_idx  <= Nr - 1;          -- first emitted index = N-1
                cap_seen <= '1';
                if (Nr - 1) < Kr then
                  acc := sat_add(to_integer(signed(cd_xe)),
                                 chs_mem(Nr-1), ACC_MIN, ACC_MAX);
                  ce_mem(Nr-1) <= sat_clip(acc, EXT_MIN, EXT_MAX);
                end if;
              else
                if (cap_idx - 1) < Kr then
                  acc := sat_add(to_integer(signed(cd_xe)),
                                 chs_mem(cap_idx-1), ACC_MIN, ACC_MAX);
                  ce_mem(cap_idx-1) <= sat_clip(acc, EXT_MIN, EXT_MAX);
                end if;
                cap_idx <= cap_idx - 1;
              end if;
            end if;
            if cd_done = '1' then
              h_cnt <= h_cnt + 1;
              st    <= S_HALF_DISPATCH;
            end if;

          -- =================== LOWER half =============================
          -- PI1 (S_LO_ILV): gather x'_a body = c_e[pi[k]] into xpa_body
          -- (forward k order). Pulse qi_start, then consume the pi stream.
          when S_LO_PI1_START =>
            qi_start <= '1';          -- d0c/stepc cached from S_ROM_WAIT
            pi_k     <= 0;
            st       <= S_LO_PI1;

          when S_LO_PI1 =>
            if qi_valid = '1' then
              pi_idx := to_integer(unsigned(qi_pi));
              -- x'_a[pi_k] core-input body = c_e[pi_idx], re-quantized to W_IN.
              xpa_body(pi_k) <= sat_clip(ce_mem(pi_idx), IN_MIN, IN_MAX);
              if qi_last = '1' then
                cd_start <= '1';      -- start the lower core run
                feed_idx <= 0;
                cap_idx  <= 0;
                cap_seen <= '0';
                st       <= S_LO_DEC;
              else
                pi_k <= pi_k + 1;
              end if;
            end if;

          -- LOWER core run: feed x'_a body (0..K-1) + xpa_term, z'_a;
          -- capture x'_e (reverse order) into xpe_body[k]=sat_to_ext(x'_e[k]).
          when S_LO_DEC =>
            if feed_idx < Nr then
              if feed_idx < Kr then
                xa_v := sat_clip(xpa_body(feed_idx), IN_MIN, IN_MAX);
              else
                xa_v := xpa_term(feed_idx - Kr);
              end if;
              za_v := zpa_mem(feed_idx);
              cd_xa       <= std_logic_vector(to_signed(xa_v, W_IN));
              cd_za       <= std_logic_vector(to_signed(za_v, W_IN));
              cd_in_valid <= '1';
              feed_idx    <= feed_idx + 1;
            end if;
            if cd_out_valid = '1' then
              xe_code := to_integer(signed(cd_xe));
              if cap_seen = '0' then
                cap_idx  <= Nr - 1;
                cap_seen <= '1';
                if (Nr - 1) < Kr then
                  xpe_body(Nr-1) <= sat_clip(xe_code, EXT_MIN, EXT_MAX);
                end if;
              else
                if (cap_idx - 1) < Kr then
                  xpe_body(cap_idx-1) <= sat_clip(xe_code, EXT_MIN, EXT_MAX);
                end if;
                cap_idx <= cap_idx - 1;
              end if;
            end if;
            if cd_done = '1' then
              -- replay pi to scatter c_a[pi[k]] = x'_e[k].
              st <= S_LO_PI2_START;
            end if;

          -- PI2 (S_LO_DILV): regenerate pi, scatter c_a[pi[k]] = xpe_body[k].
          when S_LO_PI2_START =>
            qi_start <= '1';          -- d0c/stepc still cached
            pi_k     <= 0;
            st       <= S_LO_PI2;

          when S_LO_PI2 =>
            if qi_valid = '1' then
              pi_idx := to_integer(unsigned(qi_pi));
              ca_mem(pi_idx) <= xpe_body(pi_k);   -- already W_EXT-clipped
              if qi_last = '1' then
                h_cnt <= h_cnt + 1;
                st    <= S_HALF_DISPATCH;
              else
                pi_k <= pi_k + 1;
              end if;
            end if;

          -- =================== FINISH ================================
          when S_FINAL =>
            out_idx <= 0;
            st      <= S_OUT;

          -- Stream K hard bits c[k] = (c_a[k] + c_e[k]) < 0, c[0] first.
          when S_OUT =>
            acc := sat_add(ca_mem(out_idx), ce_mem(out_idx),
                           ACC_MIN, ACC_MAX);
            if acc < 0 then
              cbit <= '1';
            else
              cbit <= '0';
            end if;
            ov <= '1';
            if out_idx = Kr - 1 then
              ol <= '1';
              st <= S_DONE;
            else
              out_idx <= out_idx + 1;
            end if;

          when S_DONE =>
            bsy <= '0';
            dn  <= '1';
            st  <= S_IDLE;

        end case;
      end if;
    end if;
  end process;
end architecture rtl;
